apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: redis
spec:
  template:
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      containers:
      - image: gcr.io/google_containers/redis:v1
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
