apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: redis-sentinel
spec:
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - image: gcr.io/google_containers/redis:v1
        name: sentinel
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
